from enum import StrEnum


class PlateStatus(StrEnum):
    STATE_SALE = "STATE_SALE"
    OWNED = "OWNED"
    FIXED_SALE = "FIXED_SALE"
    AUCTION = "AUCTION"
    RESERVED = "RESERVED"


class SaleStatus(StrEnum):
    ACTIVE = "ACTIVE"
    RESERVED = "RESERVED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class AuctionStatus(StrEnum):
    CREATED = "CREATED"
    ACTIVE = "ACTIVE"
    EXTENDED = "EXTENDED"
    FINISHED = "FINISHED"
    CANCELLED = "CANCELLED"


class PaymentStatus(StrEnum):
    PENDING = "PENDING"
    PAID = "PAID"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class PaymentKind(StrEnum):
    TOP_UP = "TOP_UP"
    STATE_EMISSION = "STATE_EMISSION"
    STATE_PURCHASE = "STATE_PURCHASE"
    SALE_PURCHASE = "SALE_PURCHASE"


class TransactionType(StrEnum):
    TOP_UP = "TOP_UP"
    PURCHASE_DEBIT = "PURCHASE_DEBIT"
    SALE_CREDIT = "SALE_CREDIT"
    AUCTION_FREEZE = "AUCTION_FREEZE"
    AUCTION_UNFREEZE = "AUCTION_UNFREEZE"
    AUCTION_SETTLEMENT = "AUCTION_SETTLEMENT"
    ADMIN_ADJUSTMENT = "ADMIN_ADJUSTMENT"
    CONFISCATION = "CONFISCATION"


class OwnershipOperation(StrEnum):
    STATE_EMISSION = "STATE_EMISSION"
    SALE = "SALE"
    AUCTION = "AUCTION"
    CONFISCATION = "CONFISCATION"
    ADMIN_TRANSFER = "ADMIN_TRANSFER"


class NotificationType(StrEnum):
    AUCTION_BID_PLACED = "AUCTION_BID_PLACED"
    AUCTION_WON = "AUCTION_WON"
    AUCTION_OUTBID = "AUCTION_OUTBID"
    AUCTION_FINISHED = "AUCTION_FINISHED"
    SALE_COMPLETED = "SALE_COMPLETED"
    PLATE_PURCHASED = "PLATE_PURCHASED"
    BALANCE_TOPUP = "BALANCE_TOPUP"
    ACCOUNT_INACTIVE_WARNING = "ACCOUNT_INACTIVE_WARNING"


class UserStatus(StrEnum):
    ACTIVE = "ACTIVE"
    BLOCKED = "BLOCKED"
    INACTIVE = "INACTIVE"
    ADMIN = "ADMIN"


class Screen(StrEnum):
    HOME = "HOME"
    SEARCH = "SEARCH"
    SEARCH_RESULTS = "SEARCH_RESULTS"
    MARKET = "MARKET"
    MARKET_RU = "MARKET_RU"
    MARKET_KZ = "MARKET_KZ"
    PLATE_VIEW = "PLATE_VIEW"
    MY_PLATES = "MY_PLATES"
    MY_PLATE_VIEW = "MY_PLATE_VIEW"
    CREATE_SALE = "CREATE_SALE"
    CREATE_AUCTION = "CREATE_AUCTION"
    AUCTIONS = "AUCTIONS"
    AUCTION_VIEW = "AUCTION_VIEW"
    AUCTION_HISTORY = "AUCTION_HISTORY"
    BALANCE = "BALANCE"
    BALANCE_TOPUP = "BALANCE_TOPUP"
    PROFILE = "PROFILE"
    HELP = "HELP"
    LEGAL = "LEGAL"
    ADMIN_HOME = "ADMIN_HOME"
    ADMIN_STATS = "ADMIN_STATS"
    ADMIN_USERS = "ADMIN_USERS"
    ADMIN_USER_VIEW = "ADMIN_USER_VIEW"
    ADMIN_PLATES = "ADMIN_PLATES"
    ADMIN_PLATE_VIEW = "ADMIN_PLATE_VIEW"
    ADMIN_AUCTIONS = "ADMIN_AUCTIONS"
    ADMIN_AUCTION_VIEW = "ADMIN_AUCTION_VIEW"
    ADMIN_FINANCE = "ADMIN_FINANCE"
    ADMIN_BLACKLISTS = "ADMIN_BLACKLISTS"
    ADMIN_CARDS = "ADMIN_CARDS"
    ADMIN_SETTINGS = "ADMIN_SETTINGS"
    ADMIN_BACKUPS = "ADMIN_BACKUPS"
